core:
  grav:
    version: 1.8.0-beta.4
    schema: 1.7.0_2020-11-20_1
    history:
      - { version: 1.8.0-beta.4, date: '2025-07-20 04:53:53' }
      - { version: 1.8.0-beta.4, date: '2025-07-20 04:56:34' }
