<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEEzbBj8\AppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEEzbBj8/AppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerEEzbBj8.legacy');

    return;
}

if (!\class_exists(AppKernelProdContainer::class, false)) {
    \class_alias(\ContainerEEzbBj8\AppKernelProdContainer::class, AppKernelProdContainer::class, false);
}

return new \ContainerEEzbBj8\AppKernelProdContainer([
    'container.build_hash' => 'EEzbBj8',
    'container.build_id' => '309221da',
    'container.build_time' => 1752981970,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEEzbBj8');
