<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZhNpzlaService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.ZhNpzla' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZhNpzla'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'companyModel' => ['services', 'Mautic\\LeadBundle\\Model\\CompanyModel', 'getCompanyModelService', false],
            'leadModel' => ['services', 'Mautic\\LeadBundle\\Model\\LeadModel', 'getLeadModelService', false],
        ], [
            'companyModel' => 'Mautic\\LeadBundle\\Model\\CompanyModel',
            'leadModel' => 'Mautic\\LeadBundle\\Model\\LeadModel',
        ]);
    }
}
