<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZmT9zEeService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.zmT9zEe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zmT9zEe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactRequestHelper' => ['services', 'Mautic\\LeadBundle\\Helper\\ContactRequestHelper', 'getContactRequestHelperService', false],
            'deviceTrackingService' => ['services', 'mautic.lead.service.device_tracking_service', 'getMautic_Lead_Service_DeviceTrackingServiceService', false],
            'helper' => ['services', 'mautic.helper.dynamicContent', 'getMautic_Helper_DynamicContentService', true],
        ], [
            'contactRequestHelper' => 'Mautic\\LeadBundle\\Helper\\ContactRequestHelper',
            'deviceTrackingService' => '?',
            'helper' => '?',
        ]);
    }
}
