<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IK_TABEService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.IK.TABE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.IK.TABE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'hasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', false],
            'languageHelper' => ['services', 'Mautic\\CoreBundle\\Helper\\LanguageHelper', 'getLanguageHelperService', true],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'hasher' => '?',
            'languageHelper' => 'Mautic\\CoreBundle\\Helper\\LanguageHelper',
            'tokenStorage' => '?',
        ]);
    }
}
