<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LllcEaXService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.lllcEaX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lllcEaX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactTracker' => ['services', 'Mautic\\LeadBundle\\Tracker\\ContactTracker', 'getContactTrackerService', false],
        ], [
            'contactTracker' => 'Mautic\\LeadBundle\\Tracker\\ContactTracker',
        ]);
    }
}
