<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U6WC8PsService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.U6WC8Ps' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U6WC8Ps'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'tagDependencies' => ['services', 'MauticPlugin\\MauticTagManagerBundle\\Stats\\TagDependencies', 'getTagDependenciesService', true],
        ], [
            'tagDependencies' => 'MauticPlugin\\MauticTagManagerBundle\\Stats\\TagDependencies',
        ]);
    }
}
