<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KFGIRJfService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.kFGIRJf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kFGIRJf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailModel' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', false],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'emailModel' => 'Mautic\\EmailBundle\\Model\\EmailModel',
            'formFactory' => '?',
            'twig' => '?',
        ]);
    }
}
