<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WGGvHF0Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.wGGvHF0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wGGvHF0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mailHelper' => ['services', 'Mautic\\EmailBundle\\Helper\\MailHelper', 'getMailHelperService', false],
            'model' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
        ], [
            'mailHelper' => 'Mautic\\EmailBundle\\Helper\\MailHelper',
            'model' => 'Mautic\\EmailBundle\\Model\\EmailModel',
        ]);
    }
}
