<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YQM9hE_Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.YQM9hE.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YQM9hE.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'twig' => ['privates', 'twig', 'getTwigService', false],
            'widgetService' => ['services', 'mautic.dashboard.widget', 'getMautic_Dashboard_WidgetService', true],
        ], [
            'twig' => '?',
            'widgetService' => '?',
        ]);
    }
}
