<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EFn9MGzService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.EFn9MGz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EFn9MGz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'model' => ['services', 'Mautic\\UserBundle\\Model\\RoleModel', 'getRoleModelService', false],
        ], [
            'model' => 'Mautic\\UserBundle\\Model\\RoleModel',
        ]);
    }
}
