<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_3bCsxdvService extends AppKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.3bCsxdv' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.3bCsxdv'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \Mautic\MessengerBundle\MessageHandler\RemoveReportAttachmentHandler(($container->services['Mautic\\ReportBundle\\Model\\ExportHandler'] ?? $container->load('getExportHandlerService')), ($container->services['mautic.helper.file_path_resolver'] ?? self::getMautic_Helper_FilePathResolverService($container))), ['priority' => -1000]);
    }
}
