<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XrQkn0uService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.xrQkn0u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xrQkn0u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'analyticsHelper' => ['services', 'mautic.helper.twig.analytics', 'getMautic_Helper_Twig_AnalyticsService', false],
            'assetsHelper' => ['services', 'Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper', 'getAssetsHelperService', false],
            'contactRequestHelper' => ['services', 'Mautic\\LeadBundle\\Helper\\ContactRequestHelper', 'getContactRequestHelperService', false],
            'cookieHelper' => ['services', 'mautic.helper.cookie', 'getMautic_Helper_CookieService', false],
            'deviceTrackingService' => ['services', 'mautic.lead.service.device_tracking_service', 'getMautic_Lead_Service_DeviceTrackingServiceService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'themeHelper' => ['services', 'mautic.helper.theme', 'getMautic_Helper_ThemeService', false],
            'tracking404Model' => ['services', 'Mautic\\PageBundle\\Model\\Tracking404Model', 'getTracking404ModelService', true],
        ], [
            'analyticsHelper' => '?',
            'assetsHelper' => 'Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper',
            'contactRequestHelper' => 'Mautic\\LeadBundle\\Helper\\ContactRequestHelper',
            'cookieHelper' => '?',
            'deviceTrackingService' => '?',
            'router' => '?',
            'themeHelper' => '?',
            'tracking404Model' => 'Mautic\\PageBundle\\Model\\Tracking404Model',
        ]);
    }
}
