<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QxSmuiMService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.QxSmuiM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.QxSmuiM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'assetModel' => ['services', 'Mautic\\AssetBundle\\Model\\AssetModel', 'getAssetModelService', false],
        ], [
            'assetModel' => 'Mautic\\AssetBundle\\Model\\AssetModel',
        ]);
    }
}
