<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_V3E0A3Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.V3E0A3_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.V3E0A3_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactColumnsDictionary' => ['services', 'mautic.lead.columns.dictionary', 'getMautic_Lead_Columns_DictionaryService', true],
            'leadDNCModel' => ['services', 'Mautic\\LeadBundle\\Model\\DoNotContact', 'getDoNotContactService', false],
        ], [
            'contactColumnsDictionary' => '?',
            'leadDNCModel' => 'Mautic\\LeadBundle\\Model\\DoNotContact',
        ]);
    }
}
