<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__Ua3LHAService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator..ua3LHA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..ua3LHA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'lookupHelper' => ['services', 'mautic.plugin.clearbit.lookup_helper', 'getMautic_Plugin_Clearbit_LookupHelperService', true],
            'mauticLogger' => ['services', 'monolog.logger.mautic', 'getMonolog_Logger_MauticService', false],
        ], [
            'lookupHelper' => '?',
            'mauticLogger' => '?',
        ]);
    }
}
