<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VKju6JEService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.vKju6JE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vKju6JE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doNotContact' => ['services', 'Mautic\\LeadBundle\\Model\\DoNotContact', 'getDoNotContactService', false],
            'emailModel' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
        ], [
            'doNotContact' => 'Mautic\\LeadBundle\\Model\\DoNotContact',
            'emailModel' => 'Mautic\\EmailBundle\\Model\\EmailModel',
        ]);
    }
}
