<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9CljUXWService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9CljUXW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9CljUXW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ipServiceFactory' => ['services', 'mautic.ip_lookup.factory', 'getMautic_IpLookup_FactoryService', false],
        ], [
            'ipServiceFactory' => '?',
        ]);
    }
}
