<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XXdjDxZService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.xXdjDxZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xXdjDxZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'integrationHelper' => ['services', 'mautic.helper.integration', 'getMautic_Helper_IntegrationService', false],
            'model' => ['services', 'Mautic\\AssetBundle\\Model\\AssetModel', 'getAssetModelService', false],
            'parametersHelper' => ['services', 'mautic.helper.core_parameters', 'getMautic_Helper_CoreParametersService', false],
            'uploaderHelper' => ['services', 'oneup_uploader.templating.uploader_helper', 'getOneupUploader_Templating_UploaderHelperService', false],
        ], [
            'integrationHelper' => '?',
            'model' => 'Mautic\\AssetBundle\\Model\\AssetModel',
            'parametersHelper' => '?',
            'uploaderHelper' => '?',
        ]);
    }
}
