<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FLQqHO4Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.FLQqHO4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FLQqHO4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'actionModel' => ['services', 'Mautic\\EmailBundle\\Model\\EmailActionModel', 'getEmailActionModelService', true],
            'categoryModel' => ['services', 'Mautic\\CategoryBundle\\Model\\CategoryModel', 'getCategoryModelService', false],
        ], [
            'actionModel' => 'Mautic\\EmailBundle\\Model\\EmailActionModel',
            'categoryModel' => 'Mautic\\CategoryBundle\\Model\\CategoryModel',
        ]);
    }
}
