<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MoFv4F8Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.moFv4F8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.moFv4F8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', false],
            'pageModel' => ['services', 'Mautic\\PageBundle\\Model\\PageModel', 'getPageModelService', false],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'formFactory' => '?',
            'pageModel' => 'Mautic\\PageBundle\\Model\\PageModel',
            'twig' => '?',
        ]);
    }
}
