<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OIeJ9u5Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.oIeJ9u5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oIeJ9u5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dateFromObject' => ['privates', '.errored..service_locator.oIeJ9u5.DateTimeImmutable', NULL, 'Cannot autowire service ".service_locator.oIeJ9u5": it references class "DateTimeImmutable" but no such service exists.'],
            'dateToObject' => ['privates', '.errored..service_locator.oIeJ9u5.DateTimeImmutable', NULL, 'Cannot autowire service ".service_locator.oIeJ9u5": it references class "DateTimeImmutable" but no such service exists.'],
            'entity' => ['privates', '.errored..service_locator.oIeJ9u5.Mautic\\EmailBundle\\Entity\\Email', NULL, 'Cannot autowire service ".service_locator.oIeJ9u5": it needs an instance of "Mautic\\EmailBundle\\Entity\\Email" but this type has been excluded in "Config/services.php".'],
        ], [
            'dateFromObject' => 'DateTimeImmutable',
            'dateToObject' => 'DateTimeImmutable',
            'entity' => 'Mautic\\EmailBundle\\Entity\\Email',
        ]);
    }
}
