<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_UiuAQ4F_DateTimeImmutableService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.uiuAQ4F.DateTimeImmutable' shared service.
     *
     * @return \DateTimeImmutable
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uiuAQ4F": it references class "DateTimeImmutable" but no such service exists.');
    }
}
