<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XHAdJVService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.X_HAdJV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X_HAdJV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bus' => ['services', 'messenger.default_bus', 'getMessenger_DefaultBusService', false],
            'messageFactory' => ['privates', 'Mautic\\MessengerBundle\\Service\\TestMessageFactory', 'getTestMessageFactoryService', true],
        ], [
            'bus' => '?',
            'messageFactory' => 'Mautic\\MessengerBundle\\Service\\TestMessageFactory',
        ]);
    }
}
