<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H3TB6CService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.H_3TB6C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.H_3TB6C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'bundleHelper' => ['services', 'mautic.helper.bundle', 'getMautic_Helper_BundleService', false],
            'cacheHelper' => ['services', 'mautic.helper.cache', 'getMautic_Helper_CacheService', false],
            'configMapper' => ['services', 'Mautic\\ConfigBundle\\Mapper\\ConfigMapper', 'getConfigMapperService', true],
            'configurator' => ['services', 'mautic.configurator', 'getMautic_ConfiguratorService', false],
            'pathsHelper' => ['services', 'mautic.helper.paths', 'getMautic_Helper_PathsService', false],
            'tokenStorage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
        ], [
            'bundleHelper' => '?',
            'cacheHelper' => '?',
            'configMapper' => 'Mautic\\ConfigBundle\\Mapper\\ConfigMapper',
            'configurator' => '?',
            'pathsHelper' => '?',
            'tokenStorage' => '?',
        ]);
    }
}
