<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZFCQ5MgService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.zFCQ5Mg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zFCQ5Mg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entity' => ['privates', '.errored..service_locator.zFCQ5Mg.Mautic\\CampaignBundle\\Entity\\Campaign', NULL, 'Cannot autowire service ".service_locator.zFCQ5Mg": it needs an instance of "Mautic\\CampaignBundle\\Entity\\Campaign" but this type has been excluded in "Config/services.php".'],
        ], [
            'entity' => 'Mautic\\CampaignBundle\\Entity\\Campaign',
        ]);
    }
}
