<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0YpBH7MService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.0YpBH7M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0YpBH7M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ipLookupHelper' => ['services', 'mautic.helper.ip_lookup', 'getMautic_Helper_IpLookupService', false],
            'monitoring' => ['privates', '.errored..service_locator.0YpBH7M.MauticPlugin\\MauticSocialBundle\\Entity\\Monitoring', NULL, 'Cannot autowire service ".service_locator.0YpBH7M": it needs an instance of "MauticPlugin\\MauticSocialBundle\\Entity\\Monitoring" but this type has been excluded in "Config/services.php".'],
        ], [
            'ipLookupHelper' => '?',
            'monitoring' => 'MauticPlugin\\MauticSocialBundle\\Entity\\Monitoring',
        ]);
    }
}
