<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QEJHc4dService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.qEJHc4d' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qEJHc4d'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailConfig' => ['services', 'Mautic\\EmailBundle\\Helper\\EmailConfig', 'getEmailConfigService', true],
            'model' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
        ], [
            'emailConfig' => 'Mautic\\EmailBundle\\Helper\\EmailConfig',
            'model' => 'Mautic\\EmailBundle\\Model\\EmailModel',
        ]);
    }
}
