<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_A7n_BP8Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.A7n.BP8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A7n.BP8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', false],
            'pathsHelper' => ['services', 'mautic.helper.paths', 'getMautic_Helper_PathsService', false],
            'urlGenerator' => ['services', 'router', 'getRouterService', false],
            'widget' => ['services', 'mautic.dashboard.widget', 'getMautic_Dashboard_WidgetService', true],
        ], [
            'formFactory' => '?',
            'pathsHelper' => '?',
            'urlGenerator' => '?',
            'widget' => '?',
        ]);
    }
}
