<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9KhSp3NService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9KhSp3N' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9KhSp3N'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contactTracker' => ['services', 'Mautic\\LeadBundle\\Tracker\\ContactTracker', 'getContactTrackerService', false],
            'trackedDeviceService' => ['services', 'mautic.lead.service.device_tracking_service', 'getMautic_Lead_Service_DeviceTrackingServiceService', false],
        ], [
            'contactTracker' => 'Mautic\\LeadBundle\\Tracker\\ContactTracker',
            'trackedDeviceService' => '?',
        ]);
    }
}
