<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_KdzFuIuService extends AppKernelProdContainer
{
    /*
     * Gets the private '.messenger.handler_descriptor.KdzFuIu' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.messenger.handler_descriptor.KdzFuIu'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(($container->privates['Mautic\\MessengerBundle\\MessageHandler\\TestHandler'] ?? $container->load('getTestHandlerService'))->handleFailed(...), ['method' => 'handleFailed']);
    }
}
