<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WhkCbQ0Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.WhkCbQ0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WhkCbQ0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fileManager' => ['services', 'grapesjsbuilder.helper.filemanager', 'getGrapesjsbuilder_Helper_FilemanagerService', true],
        ], [
            'fileManager' => '?',
        ]);
    }
}
