<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WsD63jeService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.WsD63je' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WsD63je'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'pageHelperFactory' => ['services', 'mautic.page.helper.factory', 'getMautic_Page_Helper_FactoryService', true],
        ], [
            'pageHelperFactory' => '?',
        ]);
    }
}
