<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZEozTH5Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.zEozTH5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zEozTH5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fakeLeadHelper' => ['services', 'Mautic\\LeadBundle\\Helper\\FakeContactHelper', 'getFakeContactHelperService', true],
            'leadModel' => ['services', 'Mautic\\LeadBundle\\Model\\LeadModel', 'getLeadModelService', false],
            'model' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
            'security' => ['services', 'mautic.security', 'getMautic_SecurityService', false],
        ], [
            'fakeLeadHelper' => 'Mautic\\LeadBundle\\Helper\\FakeContactHelper',
            'leadModel' => 'Mautic\\LeadBundle\\Model\\LeadModel',
            'model' => 'Mautic\\EmailBundle\\Model\\EmailModel',
            'security' => '?',
        ]);
    }
}
