<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EMoR0XAService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.eMoR0XA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eMoR0XA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'emailModel' => ['services', 'Mautic\\EmailBundle\\Model\\EmailModel', 'getEmailModelService', false],
            'leadModel' => ['services', 'Mautic\\LeadBundle\\Model\\LeadModel', 'getLeadModelService', false],
            'mailHelper' => ['services', 'Mautic\\EmailBundle\\Helper\\MailHelper', 'getMailHelperService', false],
            'userHelper' => ['services', 'mautic.helper.user', 'getMautic_Helper_UserService', false],
        ], [
            'emailModel' => 'Mautic\\EmailBundle\\Model\\EmailModel',
            'leadModel' => 'Mautic\\LeadBundle\\Model\\LeadModel',
            'mailHelper' => 'Mautic\\EmailBundle\\Helper\\MailHelper',
            'userHelper' => '?',
        ]);
    }
}
