<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MXfYy30Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.mXfYy30' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mXfYy30'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'cookieHelper' => ['services', 'mautic.helper.cookie', 'getMautic_Helper_CookieService', false],
            'kernel' => ['services', 'kernel', 'getKernelService', false],
        ], [
            'cookieHelper' => '?',
            'kernel' => '?',
        ]);
    }
}
