<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__HMAeBLService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator..HMAeBL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..HMAeBL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'fieldValidator' => ['services', 'mautic.integrations.helper.field_validator', 'getMautic_Integrations_Helper_FieldValidatorService', true],
            'formExtension' => ['services', 'Mautic\\CoreBundle\\Twig\\Extension\\FormExtension', 'getFormExtensionService', false],
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', false],
            'integrationsHelper' => ['services', 'mautic.integrations.helper.config_integrations', 'getMautic_Integrations_Helper_ConfigIntegrationsService', true],
        ], [
            'dispatcher' => '?',
            'fieldValidator' => '?',
            'formExtension' => 'Mautic\\CoreBundle\\Twig\\Extension\\FormExtension',
            'formFactory' => '?',
            'integrationsHelper' => '?',
        ]);
    }
}
