<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9MPTg3Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.9M_pTg3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9M_pTg3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', false],
            'integrationsHelper' => ['services', 'mautic.integrations.helper.config_integrations', 'getMautic_Integrations_Helper_ConfigIntegrationsService', true],
        ], [
            'formFactory' => '?',
            'integrationsHelper' => '?',
        ]);
    }
}
