<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YCBXCJ7Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.yCBXCJ7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yCBXCJ7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'model' => ['services', 'Mautic\\ReportBundle\\Model\\ReportModel', 'getReportModelService', true],
        ], [
            'model' => 'Mautic\\ReportBundle\\Model\\ReportModel',
        ]);
    }
}
