<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Security_RequestMatcher_Y5tdRe0Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.security.request_matcher.Y5tdRe0' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\ChainRequestMatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.security.request_matcher.Y5tdRe0'] = new \Symfony\Component\HttpFoundation\ChainRequestMatcher([($container->privates['.security.request_matcher.Kohv6IY'] ??= new \Symfony\Component\HttpFoundation\RequestMatcher\PathRequestMatcher('^/installer'))]);
    }
}
