<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_L8n0CI8Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.l8n0CI8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.l8n0CI8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trailingSlashHelper' => ['services', 'mautic.helper.trailing_slash', 'getMautic_Helper_TrailingSlashService', true],
        ], [
            'trailingSlashHelper' => '?',
        ]);
    }
}
