<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7UA8OZQService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.7UA8OZQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7UA8OZQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mauticLogger' => ['services', 'monolog.logger.mautic', 'getMonolog_Logger_MauticService', false],
            'transportChain' => ['services', 'mautic.sms.transport_chain', 'getMautic_Sms_TransportChainService', true],
        ], [
            'mauticLogger' => '?',
            'transportChain' => '?',
        ]);
    }
}
