<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XwHNNPService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator._xwHNNP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._xwHNNP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'formFactory' => ['privates', 'form.factory', 'getForm_FactoryService', false],
            'monitoringModel' => ['services', 'MauticPlugin\\MauticSocialBundle\\Model\\MonitoringModel', 'getMonitoringModelService', true],
        ], [
            'formFactory' => '?',
            'monitoringModel' => 'MauticPlugin\\MauticSocialBundle\\Model\\MonitoringModel',
        ]);
    }
}
