<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Yec6C9cService extends AppKernelProdContainer
{
    /*
     * Gets the private '.service_locator.yec6C9c' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.yec6C9c'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'fieldAliasHelper' => ['services', 'mautic.helper.field.alias', 'getMautic_Helper_Field_AliasService', true],
            'fieldModel' => ['services', 'Mautic\\LeadBundle\\Model\\FieldModel', 'getFieldModel2Service', false],
        ], [
            'fieldAliasHelper' => '?',
            'fieldModel' => 'Mautic\\LeadBundle\\Model\\FieldModel',
        ]);
    }
}
