<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorizeControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ApiBundle\Controller\oAuth2\AuthorizeController' shared autowired service.
     *
     * @return \Mautic\ApiBundle\Controller\oAuth2\AuthorizeController
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\ApiBundle\\Controller\\oAuth2\\AuthorizeController'] = new \Mautic\ApiBundle\Controller\oAuth2\AuthorizeController(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->privates['fos_oauth_server.authorize.form'] ?? $container->load('getFosOauthServer_Authorize_FormService')), ($container->privates['fos_oauth_server.authorize.form.handler.default'] ?? $container->load('getFosOauthServer_Authorize_Form_Handler_DefaultService')), ($container->privates['fos_oauth_server.server'] ?? $container->load('getFosOauthServer_ServerService')), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['fos_oauth_server.client_manager.default'] ?? $container->load('getFosOauthServer_ClientManager_DefaultService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->privates['twig'] ?? self::getTwigService($container)));
    }
}
