<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApplyUpdatesCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Command\ApplyUpdatesCommand' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Command\ApplyUpdatesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Command\\ApplyUpdatesCommand'] = new \Mautic\CoreBundle\Command\ApplyUpdatesCommand(($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.update.step_provider'] ?? $container->load('getMautic_Update_StepProviderService')), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
