<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAnalyseCustomFieldCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Field\Command\AnalyseCustomFieldCommand' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Field\Command\AnalyseCustomFieldCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Field\\Command\\AnalyseCustomFieldCommand'] = new \Mautic\LeadBundle\Field\Command\AnalyseCustomFieldCommand(($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? self::getFieldModel2Service($container)), ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? self::getLeadModelService($container)), ($container->services['translator'] ?? self::getTranslator2Service($container)));
    }
}
