<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBuilderSubscriber3Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PageBundle\EventListener\BuilderSubscriber' shared autowired service.
     *
     * @return \Mautic\PageBundle\EventListener\BuilderSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'];
        }
        $b = ($container->services['Mautic\\PageBundle\\Model\\PageModel'] ?? self::getPageModelService($container));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'];
        }
        $c = ($container->services['mautic.helper.token_builder.factory'] ?? $container->load('getMautic_Helper_TokenBuilder_FactoryService'));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'];
        }
        $d = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'];
        }
        $e = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'];
        }

        return $container->services['Mautic\\PageBundle\\EventListener\\BuilderSubscriber'] = new \Mautic\PageBundle\EventListener\BuilderSubscriber(($container->services['mautic.page.helper.token'] ?? self::getMautic_Page_Helper_TokenService($container)), $a, $b, $c, ($container->services['translator'] ?? self::getTranslator2Service($container)), $d, $e, ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
