<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getButtonSubscriber2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticFullContactBundle\EventListener\ButtonSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticFullContactBundle\EventListener\ButtonSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['MauticPlugin\\MauticFullContactBundle\\EventListener\\ButtonSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFullContactBundle\\EventListener\\ButtonSubscriber'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['MauticPlugin\\MauticFullContactBundle\\EventListener\\ButtonSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFullContactBundle\\EventListener\\ButtonSubscriber'];
        }

        return $container->services['MauticPlugin\\MauticFullContactBundle\\EventListener\\ButtonSubscriber'] = new \MauticPlugin\MauticFullContactBundle\EventListener\ButtonSubscriber($a, ($container->services['translator'] ?? self::getTranslator2Service($container)), $b);
    }
}
