<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBroadcastSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EventListener\BroadcastSubscriber' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EventListener\BroadcastSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailModel'] ?? self::getEmailModelService($container));

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\BroadcastSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\BroadcastSubscriber'];
        }

        return $container->services['Mautic\\EmailBundle\\EventListener\\BroadcastSubscriber'] = new \Mautic\EmailBundle\EventListener\BroadcastSubscriber($a, ($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)), ($container->services['translator'] ?? self::getTranslator2Service($container)));
    }
}
