<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignEventLeadFieldValueTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Form\Type\CampaignEventLeadFieldValueType' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Form\Type\CampaignEventLeadFieldValueType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? self::getLeadModelService($container));

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventLeadFieldValueType'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventLeadFieldValueType'];
        }
        $b = ($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? self::getFieldModel2Service($container));

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventLeadFieldValueType'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventLeadFieldValueType'];
        }

        return $container->services['Mautic\\LeadBundle\\Form\\Type\\CampaignEventLeadFieldValueType'] = new \Mautic\LeadBundle\Form\Type\CampaignEventLeadFieldValueType(($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), $a, $b);
    }
}
