<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyApiControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Controller\Api\CompanyApiController' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Controller\Api\CompanyApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());

        $container->services['Mautic\\LeadBundle\\Controller\\Api\\CompanyApiController'] = $instance = new \Mautic\LeadBundle\Controller\Api\CompanyApiController(($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.api.helper.entity_result'] ??= new \Mautic\ApiBundle\Helper\EntityResultHelper()), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['form.factory'] ?? self::getForm_FactoryService($container)), ($container->services['mautic.helper.app_version'] ??= new \Mautic\CoreBundle\Helper\AppVersion()), $a, ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));

        $instance->setContainer(($container->privates['.service_locator.JkaYaOo'] ?? $container->load('get_ServiceLocator_JkaYaOoService'))->withContext('Mautic\\LeadBundle\\Controller\\Api\\CompanyApiController', $container));
        $instance->setRequestStack($a);

        return $instance;
    }
}
