<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_FosOauthServer_CleanCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.fos_oauth_server.clean_command' shared service.
     *
     * @return \FOS\OAuthServerBundle\Command\CleanCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.fos_oauth_server.clean_command'] = new \FOS\OAuthServerBundle\Command\CleanCommand(($container->privates['fos_oauth_server.access_token_manager.default'] ?? $container->load('getFosOauthServer_AccessTokenManager_DefaultService')), ($container->privates['fos_oauth_server.refresh_token_manager.default'] ?? $container->load('getFosOauthServer_RefreshTokenManager_DefaultService')), ($container->privates['fos_oauth_server.auth_code_manager.default'] ?? $container->load('getFosOauthServer_AuthCodeManager_DefaultService')));
    }
}
