<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanyReportDataService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Model\CompanyReportData' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Model\CompanyReportData
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? self::getFieldModel2Service($container));

        if (isset($container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'])) {
            return $container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'];
        }

        return $container->services['Mautic\\LeadBundle\\Model\\CompanyReportData'] = new \Mautic\LeadBundle\Model\CompanyReportData($a, ($container->services['translator'] ?? self::getTranslator2Service($container)));
    }
}
