<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsole_Command_PublicAlias_FosOauthServer_CreateClientCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'console.command.public_alias.fos_oauth_server.create_client_command' shared service.
     *
     * @return \FOS\OAuthServerBundle\Command\CreateClientCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['console.command.public_alias.fos_oauth_server.create_client_command'] = new \FOS\OAuthServerBundle\Command\CreateClientCommand(($container->privates['fos_oauth_server.client_manager.default'] ?? $container->load('getFosOauthServer_ClientManager_DefaultService')));
    }
}
