<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCompanySubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\CompanySubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\CompanySubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Model\\AuditLogModel'] ?? self::getAuditLogModelService($container));

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\CompanySubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\CompanySubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\CompanySubscriber'] = new \Mautic\LeadBundle\EventListener\CompanySubscriber(($container->services['mautic.helper.ip_lookup'] ?? self::getMautic_Helper_IpLookupService($container)), $a);
    }
}
