<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigType6Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Type\ConfigType' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Type\ConfigType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Form\\Type\\ConfigType'] = new \Mautic\CoreBundle\Form\Type\ConfigType(($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['Mautic\\CoreBundle\\Helper\\LanguageHelper'] ?? $container->load('getLanguageHelperService')), ($container->services['mautic.ip_lookup.factory'] ?? self::getMautic_IpLookup_FactoryService($container)), ($container->services['mautic.ip_lookup'] ?? self::getMautic_IpLookupService($container)), ($container->services['Mautic\\CoreBundle\\Shortener\\Shortener'] ?? self::getShortenerService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
