<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConfigService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticSocialBundle\Integration\Config' shared autowired service.
     *
     * @return \MauticPlugin\MauticSocialBundle\Integration\Config
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['MauticPlugin\\MauticSocialBundle\\Integration\\Config'])) {
            return $container->services['MauticPlugin\\MauticSocialBundle\\Integration\\Config'];
        }

        return $container->services['MauticPlugin\\MauticSocialBundle\\Integration\\Config'] = new \MauticPlugin\MauticSocialBundle\Integration\Config($a);
    }
}
