<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getContentPreviewSettingsTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Type\ContentPreviewSettingsType' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Type\ContentPreviewSettingsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Form\\Type\\ContentPreviewSettingsType'] = new \Mautic\CoreBundle\Form\Type\ContentPreviewSettingsType(($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)));
    }
}
