<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCacheControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\MarketplaceBundle\Controller\CacheController' shared autowired service.
     *
     * @return \Mautic\MarketplaceBundle\Controller\CacheController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Mautic\\MarketplaceBundle\\Controller\\CacheController'] = $instance = new \Mautic\MarketplaceBundle\Controller\CacheController(($container->services['marketplace.service.config'] ?? self::getMarketplace_Service_ConfigService($container)), ($container->services['marketplace.service.allowlist'] ?? $container->load('getMarketplace_Service_AllowlistService')), ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.core.service.flashbag'] ?? self::getMautic_Core_Service_FlashbagService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('Mautic\\MarketplaceBundle\\Controller\\CacheController', $container));

        return $instance;
    }
}
