<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChannelSubscriber4Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\NotificationBundle\EventListener\ChannelSubscriber' shared autowired service.
     *
     * @return \Mautic\NotificationBundle\EventListener\ChannelSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['Mautic\\NotificationBundle\\EventListener\\ChannelSubscriber'])) {
            return $container->services['Mautic\\NotificationBundle\\EventListener\\ChannelSubscriber'];
        }

        return $container->services['Mautic\\NotificationBundle\\EventListener\\ChannelSubscriber'] = new \Mautic\NotificationBundle\EventListener\ChannelSubscriber($a);
    }
}
