<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClientSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\ApiBundle\EventListener\ClientSubscriber' shared autowired service.
     *
     * @return \Mautic\ApiBundle\EventListener\ClientSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Model\\AuditLogModel'] ?? self::getAuditLogModelService($container));

        if (isset($container->services['Mautic\\ApiBundle\\EventListener\\ClientSubscriber'])) {
            return $container->services['Mautic\\ApiBundle\\EventListener\\ClientSubscriber'];
        }

        return $container->services['Mautic\\ApiBundle\\EventListener\\ClientSubscriber'] = new \Mautic\ApiBundle\EventListener\ClientSubscriber(($container->services['mautic.helper.ip_lookup'] ?? self::getMautic_Helper_IpLookupService($container)), $a);
    }
}
