<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaign3Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.zFCQ5Mg.Mautic\CampaignBundle\Entity\Campaign' shared service.
     *
     * @return \Mautic\CampaignBundle\Entity\Campaign
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.zFCQ5Mg": it needs an instance of "Mautic\\CampaignBundle\\Entity\\Campaign" but this type has been excluded in "Config/services.php".');
    }
}
