<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignApiControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Controller\Api\CampaignApiController' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Controller\Api\CampaignApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Mautic\\CampaignBundle\\Controller\\Api\\CampaignApiController'] = $instance = new \Mautic\CampaignBundle\Controller\Api\CampaignApiController(($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.api.helper.entity_result'] ??= new \Mautic\ApiBundle\Helper\EntityResultHelper()), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['form.factory'] ?? self::getForm_FactoryService($container)), ($container->services['mautic.helper.app_version'] ??= new \Mautic\CoreBundle\Helper\AppVersion()), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['mautic.campaign.membership.manager'] ?? self::getMautic_Campaign_Membership_ManagerService($container)), ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)), ($container->privates['validator'] ?? self::getValidatorService($container)), ($container->services['Mautic\\CampaignBundle\\Model\\EventModel'] ?? $container->load('getEventModelService')));

        $instance->setContainer(($container->privates['.service_locator.JkaYaOo'] ?? $container->load('get_ServiceLocator_JkaYaOoService'))->withContext('Mautic\\CampaignBundle\\Controller\\Api\\CampaignApiController', $container));

        return $instance;
    }
}
