<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCampaignMapStatsControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Controller\CampaignMapStatsController' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Controller\CampaignMapStatsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Mautic\\CampaignBundle\\Controller\\CampaignMapStatsController'] = $instance = new \Mautic\CampaignBundle\Controller\CampaignMapStatsController(($container->services['Mautic\\CampaignBundle\\Model\\CampaignModel'] ?? self::getCampaignModelService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('Mautic\\CampaignBundle\\Controller\\CampaignMapStatsController', $container));

        return $instance;
    }
}
