<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDefaultControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'LightSaml\SpBundle\Controller\DefaultController' shared autowired service.
     *
     * @return \LightSaml\SpBundle\Controller\DefaultController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['LightSaml\\SpBundle\\Controller\\DefaultController'] = $instance = new \LightSaml\SpBundle\Controller\DefaultController();

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'form.factory' => ['privates', 'form.factory', 'getForm_FactoryService', false],
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'lightsaml.container.build' => ['services', 'lightsaml.container.build', 'getLightsaml_Container_BuildService', true],
            'ligthsaml.profile.login_factory' => ['services', 'ligthsaml.profile.login_factory', 'getLigthsaml_Profile_LoginFactoryService', true],
            'ligthsaml.profile.metadata' => ['services', 'ligthsaml.profile.metadata', 'getLigthsaml_Profile_MetadataService', true],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'security.authorization_checker' => ['services', 'jms_serializer.authorization_checker', 'getJmsSerializer_AuthorizationCheckerService', false],
            'security.csrf.token_manager' => ['privates', 'security.csrf.token_manager', 'getSecurity_Csrf_TokenManagerService', false],
            'security.token_storage' => ['privates', 'security.token_storage', 'getSecurity_TokenStorageService', false],
            'serializer' => ['privates', 'serializer', 'getSerializer2Service', false],
            'twig' => ['privates', 'twig', 'getTwigService', false],
        ], [
            'form.factory' => '?',
            'http_kernel' => '?',
            'lightsaml.container.build' => '?',
            'ligthsaml.profile.login_factory' => '?',
            'ligthsaml.profile.metadata' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'security.authorization_checker' => '?',
            'security.csrf.token_manager' => '?',
            'security.token_storage' => '?',
            'serializer' => '?',
            'twig' => '?',
        ]))->withContext('LightSaml\\SpBundle\\Controller\\DefaultController', $container));

        return $instance;
    }
}
