<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamicContentFilterTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Type\DynamicContentFilterType' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Type\DynamicContentFilterType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.integrations.helper.builder_integrations'] ?? self::getMautic_Integrations_Helper_BuilderIntegrationsService($container));

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterType'];
        }

        return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterType'] = new \Mautic\CoreBundle\Form\Type\DynamicContentFilterType($a);
    }
}
