<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardSubscriber5Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\EventListener\DashboardSubscriber' shared autowired service.
     *
     * @return \Mautic\EmailBundle\EventListener\DashboardSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailModel'] ?? self::getEmailModelService($container));

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\DashboardSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\DashboardSubscriber'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['Mautic\\EmailBundle\\EventListener\\DashboardSubscriber'])) {
            return $container->services['Mautic\\EmailBundle\\EventListener\\DashboardSubscriber'];
        }

        return $container->services['Mautic\\EmailBundle\\EventListener\\DashboardSubscriber'] = new \Mautic\EmailBundle\EventListener\DashboardSubscriber($a, $b);
    }
}
