<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeviceModelService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Model\DeviceModel' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Model\DeviceModel
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['Mautic\\LeadBundle\\Model\\DeviceModel'])) {
            return $container->services['Mautic\\LeadBundle\\Model\\DeviceModel'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['Mautic\\LeadBundle\\Model\\DeviceModel'])) {
            return $container->services['Mautic\\LeadBundle\\Model\\DeviceModel'];
        }

        return $container->services['Mautic\\LeadBundle\\Model\\DeviceModel'] = new \Mautic\LeadBundle\Model\DeviceModel(($container->services['Mautic\\LeadBundle\\Entity\\LeadDeviceRepository'] ?? self::getLeadDeviceRepositoryService($container)), ($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)), ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), $a, $b, ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['monolog.logger.mautic'] ?? self::getMonolog_Logger_MauticService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
