<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamicContentTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\DynamicContentBundle\Form\Type\DynamicContentType' shared autowired service.
     *
     * @return \Mautic\DynamicContentBundle\Form\Type\DynamicContentType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? self::getListModelService($container));

        if (isset($container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'])) {
            return $container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'];
        }
        $b = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? self::getLeadModelService($container));

        if (isset($container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'])) {
            return $container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'];
        }

        return $container->services['Mautic\\DynamicContentBundle\\Form\\Type\\DynamicContentType'] = new \Mautic\DynamicContentBundle\Form\Type\DynamicContentType(($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)), $a, ($container->services['translator'] ?? self::getTranslator2Service($container)), $b);
    }
}
