<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDynamicContentFilterEntryTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? self::getListModelService($container));

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'];
        }
        $b = ($container->services['Mautic\\StageBundle\\Model\\StageModel'] ?? $container->load('getStageModelService'));

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'];
        }
        $c = ($container->services['mautic.integrations.helper.builder_integrations'] ?? self::getMautic_Integrations_Helper_BuilderIntegrationsService($container));

        if (isset($container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'])) {
            return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'];
        }

        return $container->services['Mautic\\CoreBundle\\Form\\Type\\DynamicContentFilterEntryType'] = new \Mautic\CoreBundle\Form\Type\DynamicContentFilterEntryType($a, $b, $c);
    }
}
