<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmail2Service extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.oIeJ9u5.Mautic\EmailBundle\Entity\Email' shared service.
     *
     * @return \Mautic\EmailBundle\Entity\Email
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.oIeJ9u5": it needs an instance of "Mautic\\EmailBundle\\Entity\\Email" but this type has been excluded in "Config/services.php".');
    }
}
