<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEmailGraphStatsControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\Controller\EmailGraphStatsController' shared autowired service.
     *
     * @return \Mautic\EmailBundle\Controller\EmailGraphStatsController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['Mautic\\EmailBundle\\Controller\\EmailGraphStatsController'] = $instance = new \Mautic\EmailBundle\Controller\EmailGraphStatsController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('Mautic\\EmailBundle\\Controller\\EmailGraphStatsController', $container));

        return $instance;
    }
}
