<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormListTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\FormBundle\Form\Type\FormListType' shared autowired service.
     *
     * @return \Mautic\FormBundle\Form\Type\FormListType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\FormBundle\\Model\\FormModel'] ?? self::getFormModelService($container));

        if (isset($container->services['Mautic\\FormBundle\\Form\\Type\\FormListType'])) {
            return $container->services['Mautic\\FormBundle\\Form\\Type\\FormListType'];
        }

        return $container->services['Mautic\\FormBundle\\Form\\Type\\FormListType'] = new \Mautic\FormBundle\Form\Type\FormListType(($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), $a, ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)));
    }
}
