<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\FormBundle\Entity\FormRepository' shared autowired service.
     *
     * @return \Mautic\FormBundle\Entity\FormRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\FormBundle\\Entity\\FormRepository'] = new \Mautic\FormBundle\Entity\FormRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
