<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFieldAliasKeywordValidatorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Form\Validator\Constraints\FieldAliasKeywordValidator' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Form\Validator\Constraints\FieldAliasKeywordValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? self::getListModelService($container));

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'];
        }
        $b = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'];
        }
        $c = ($container->services['mautic.lead.repository.lead_segment_filter_descriptor'] ?? self::getMautic_Lead_Repository_LeadSegmentFilterDescriptorService($container));

        if (isset($container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'])) {
            return $container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'];
        }

        return $container->services['Mautic\\LeadBundle\\Form\\Validator\\Constraints\\FieldAliasKeywordValidator'] = new \Mautic\LeadBundle\Form\Validator\Constraints\FieldAliasKeywordValidator($a, ($container->services['mautic.helper.field.alias'] ?? $container->load('getMautic_Helper_Field_AliasService')), $b, ($container->services['translator'] ?? self::getTranslator2Service($container)), $c);
    }
}
