<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFeatureSettingsTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\Form\Type\FeatureSettingsType' shared autowired service.
     *
     * @return \Mautic\PluginBundle\Form\Type\FeatureSettingsType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PluginBundle\\Form\\Type\\FeatureSettingsType'] = new \Mautic\PluginBundle\Form\Type\FeatureSettingsType(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
