<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormSubscriber3Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\AssetBundle\EventListener\FormSubscriber' shared autowired service.
     *
     * @return \Mautic\AssetBundle\EventListener\FormSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\AssetBundle\\Model\\AssetModel'] ?? self::getAssetModelService($container));

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'];
        }
        $b = ($container->services['Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper'] ?? self::getAssetsHelperService($container));

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'];
        }
        $c = ($container->services['mautic.helper.theme'] ?? self::getMautic_Helper_ThemeService($container));

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'];
        }
        $d = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'])) {
            return $container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'];
        }

        return $container->services['Mautic\\AssetBundle\\EventListener\\FormSubscriber'] = new \Mautic\AssetBundle\EventListener\FormSubscriber($a, ($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.helper.twig.analytics'] ?? self::getMautic_Helper_Twig_AnalyticsService($container)), $b, $c, $d, ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
