<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFakeContactHelperService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Helper\FakeContactHelper' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Helper\FakeContactHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Helper\\FakeContactHelper'] = new \Mautic\LeadBundle\Helper\FakeContactHelper(($container->services['mautic.lead.field.field_list'] ?? self::getMautic_Lead_Field_FieldListService($container)));
    }
}
