<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFetchLeadsCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\Command\FetchLeadsCommand' shared autowired service.
     *
     * @return \Mautic\PluginBundle\Command\FetchLeadsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PluginBundle\\Command\\FetchLeadsCommand'] = new \Mautic\PluginBundle\Command\FetchLeadsCommand(($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container)));
    }
}
