<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupContactScoreRepositoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PointBundle\Entity\GroupContactScoreRepository' shared autowired service.
     *
     * @return \Mautic\PointBundle\Entity\GroupContactScoreRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\PointBundle\\Entity\\GroupContactScoreRepository'] = new \Mautic\PointBundle\Entity\GroupContactScoreRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
