<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGlobalSearchService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Service\GlobalSearch' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Service\GlobalSearch
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['twig'] ?? self::getTwigService($container));

        if (isset($container->services['Mautic\\CoreBundle\\Service\\GlobalSearch'])) {
            return $container->services['Mautic\\CoreBundle\\Service\\GlobalSearch'];
        }

        return $container->services['Mautic\\CoreBundle\\Service\\GlobalSearch'] = new \Mautic\CoreBundle\Service\GlobalSearch($a);
    }
}
