<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGrapesJsBuilderModelService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\GrapesJsBuilderBundle\Model\GrapesJsBuilderModel' shared autowired service.
     *
     * @return \MauticPlugin\GrapesJsBuilderBundle\Model\GrapesJsBuilderModel
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailModel'] ?? self::getEmailModelService($container));

        if (isset($container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'])) {
            return $container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'])) {
            return $container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'];
        }
        $c = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'])) {
            return $container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'];
        }

        return $container->services['MauticPlugin\\GrapesJsBuilderBundle\\Model\\GrapesJsBuilderModel'] = new \MauticPlugin\GrapesJsBuilderBundle\Model\GrapesJsBuilderModel(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, ($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)), ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), $b, $c, ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['monolog.logger.mautic'] ?? self::getMonolog_Logger_MauticService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
