<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIpLookupDownloadDataStoreButtonTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Form\Type\IpLookupDownloadDataStoreButtonType' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Form\Type\IpLookupDownloadDataStoreButtonType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Form\\Type\\IpLookupDownloadDataStoreButtonType'] = new \Mautic\CoreBundle\Form\Type\IpLookupDownloadDataStoreButtonType(($container->services['mautic.helper.twig.date'] ?? self::getMautic_Helper_Twig_DateService($container)), ($container->services['translator'] ?? self::getTranslator2Service($container)));
    }
}
