<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIndexHelperService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Field\Helper\IndexHelper' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Field\Helper\IndexHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Field\\Helper\\IndexHelper'] = new \Mautic\LeadBundle\Field\Helper\IndexHelper(($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)));
    }
}
