<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIcontactTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticEmailMarketingBundle\Form\Type\IcontactType' shared autowired service.
     *
     * @return \MauticPlugin\MauticEmailMarketingBundle\Form\Type\IcontactType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['MauticPlugin\\MauticEmailMarketingBundle\\Form\\Type\\IcontactType'])) {
            return $container->services['MauticPlugin\\MauticEmailMarketingBundle\\Form\\Type\\IcontactType'];
        }
        $b = ($container->services['Mautic\\PluginBundle\\Model\\PluginModel'] ?? self::getPluginModelService($container));

        if (isset($container->services['MauticPlugin\\MauticEmailMarketingBundle\\Form\\Type\\IcontactType'])) {
            return $container->services['MauticPlugin\\MauticEmailMarketingBundle\\Form\\Type\\IcontactType'];
        }

        return $container->services['MauticPlugin\\MauticEmailMarketingBundle\\Form\\Type\\IcontactType'] = new \MauticPlugin\MauticEmailMarketingBundle\Form\Type\IcontactType($a, $b, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
