<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getIntegrationsListTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\Form\Type\IntegrationsListType' shared autowired service.
     *
     * @return \Mautic\PluginBundle\Form\Type\IntegrationsListType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType'])) {
            return $container->services['Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType'];
        }

        return $container->services['Mautic\\PluginBundle\\Form\\Type\\IntegrationsListType'] = new \Mautic\PluginBundle\Form\Type\IntegrationsListType($a);
    }
}
