<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadSubscriber12Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PageBundle\EventListener\LeadSubscriber' shared autowired service.
     *
     * @return \Mautic\PageBundle\EventListener\LeadSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\PageBundle\\Model\\PageModel'] ?? self::getPageModelService($container));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'];
        }
        $b = ($container->services['Mautic\\PageBundle\\Model\\VideoModel'] ?? $container->load('getVideoModelService'));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'];
        }
        $c = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'];
        }
        $d = ($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container));

        if (isset($container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'];
        }

        return $container->services['Mautic\\PageBundle\\EventListener\\LeadSubscriber'] = new \Mautic\PageBundle\EventListener\LeadSubscriber($a, $b, ($container->services['translator'] ?? self::getTranslator2Service($container)), $c, $d);
    }
}
