<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadSubscriber2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticFocusBundle\EventListener\LeadSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticFocusBundle\EventListener\LeadSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\LeadSubscriber'];
        }
        $b = ($container->services['MauticPlugin\\MauticFocusBundle\\Model\\FocusModel'] ?? self::getFocusModelService($container));

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\LeadSubscriber'];
        }

        return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\LeadSubscriber'] = new \MauticPlugin\MauticFocusBundle\EventListener\LeadSubscriber(($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), $a, $b);
    }
}
