<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadApiControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Controller\Api\LeadApiController' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Controller\Api\LeadApiController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\DoNotContact'] ?? self::getDoNotContactService($container));
        $b = ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack());

        $container->services['Mautic\\LeadBundle\\Controller\\Api\\LeadApiController'] = $instance = new \Mautic\LeadBundle\Controller\Api\LeadApiController(($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.api.helper.entity_result'] ??= new \Mautic\ApiBundle\Helper\EntityResultHelper()), ($container->services['router'] ?? self::getRouterService($container)), ($container->privates['form.factory'] ?? self::getForm_FactoryService($container)), $a, ($container->services['mautic.helper.app_version'] ??= new \Mautic\CoreBundle\Helper\AppVersion()), ($container->services['mautic.lead.merger'] ?? self::getMautic_Lead_MergerService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['mautic.helper.ip_lookup'] ?? self::getMautic_Helper_IpLookupService($container)), $b, ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));

        $instance->setContainer(($container->privates['.service_locator.JkaYaOo'] ?? $container->load('get_ServiceLocator_JkaYaOoService'))->withContext('Mautic\\LeadBundle\\Controller\\Api\\LeadApiController', $container));
        $instance->setRequestStack($b);
        $instance->setDoNotContactModel($a);
        $instance->setRequestStackObject($b);
        $instance->setRequestStackLeadDetailsTrait($b);

        return $instance;
    }
}
