<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.hcsE7Ir.Mautic\LeadBundle\Entity\Lead' shared service.
     *
     * @return \Mautic\LeadBundle\Entity\Lead
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hcsE7Ir": it needs an instance of "Mautic\\LeadBundle\\Entity\\Lead" but this type has been excluded in "Config/services.php".');
    }
}
