<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLeadSubscriber15Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\SmsBundle\EventListener\LeadSubscriber' shared autowired service.
     *
     * @return \Mautic\SmsBundle\EventListener\LeadSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['Mautic\\SmsBundle\\EventListener\\LeadSubscriber'])) {
            return $container->services['Mautic\\SmsBundle\\EventListener\\LeadSubscriber'];
        }

        return $container->services['Mautic\\SmsBundle\\EventListener\\LeadSubscriber'] = new \Mautic\SmsBundle\EventListener\LeadSubscriber(($container->services['translator'] ?? self::getTranslator2Service($container)), $a, ($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)));
    }
}
