<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Helper_NotificationService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.helper.notification' shared service.
     *
     * @return \Mautic\NotificationBundle\Helper\NotificationHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }
        $b = ($container->services['Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper'] ?? self::getAssetsHelperService($container));

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }
        $c = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }
        $d = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['mautic.helper.notification'])) {
            return $container->services['mautic.helper.notification'];
        }

        return $container->services['mautic.helper.notification'] = new \Mautic\NotificationBundle\Helper\NotificationHelper($a, $b, ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)), $c, $d, ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['Mautic\\LeadBundle\\Model\\DoNotContact'] ?? self::getDoNotContactService($container)));
    }
}
