<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Lead_Segment_Stat_Campaign_ShareService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.lead.segment.stat.campaign.share' shared service.
     *
     * @return \Mautic\LeadBundle\Segment\Stat\SegmentCampaignShare
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CampaignBundle\\Model\\CampaignModel'] ?? self::getCampaignModelService($container));

        if (isset($container->services['mautic.lead.segment.stat.campaign.share'])) {
            return $container->services['mautic.lead.segment.stat.campaign.share'];
        }
        $b = ($container->services['mautic.helper.cache_storage'] ?? self::getMautic_Helper_CacheStorageService($container));

        if (isset($container->services['mautic.lead.segment.stat.campaign.share'])) {
            return $container->services['mautic.lead.segment.stat.campaign.share'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['mautic.lead.segment.stat.campaign.share'])) {
            return $container->services['mautic.lead.segment.stat.campaign.share'];
        }

        return $container->services['mautic.lead.segment.stat.campaign.share'] = new \Mautic\LeadBundle\Segment\Stat\SegmentCampaignShare($a, $b, $c);
    }
}
