<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Sync_InternalProcess_ObjectChangeGeneratorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.sync.internal_process.object_change_generator' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\SyncProcess\Direction\Internal\ObjectChangeGenerator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.integrations.sync.internal_process.object_change_generator'] = new \Mautic\IntegrationsBundle\Sync\SyncProcess\Direction\Internal\ObjectChangeGenerator(($container->services['mautic.integrations.helper.sync_judge'] ??= new \Mautic\IntegrationsBundle\Sync\SyncJudge\SyncJudge()), ($container->services['mautic.integrations.sync.sync_process.value_helper'] ??= new \Mautic\IntegrationsBundle\Sync\SyncProcess\Direction\Helper\ValueHelper()), ($container->services['Mautic\\IntegrationsBundle\\Sync\\SyncDataExchange\\Helper\\FieldHelper'] ?? $container->load('getFieldHelperService')), ($container->services['mautic.integrations.sync.notification.bulk_notification'] ?? $container->load('getMautic_Integrations_Sync_Notification_BulkNotificationService')));
    }
}
