<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Dashboard_WidgetService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.dashboard.widget' shared service.
     *
     * @return \Mautic\DashboardBundle\Dashboard\Widget
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\DashboardBundle\\Model\\DashboardModel'] ?? $container->load('getDashboardModelService'));

        if (isset($container->services['mautic.dashboard.widget'])) {
            return $container->services['mautic.dashboard.widget'];
        }

        return $container->services['mautic.dashboard.widget'] = new \Mautic\DashboardBundle\Dashboard\Widget($a, ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
