<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Page_Helper_FactoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.page.helper.factory' shared service.
     *
     * @return \Mautic\CoreBundle\Factory\PageHelperFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.page.helper.factory'] = new \Mautic\CoreBundle\Factory\PageHelperFactory(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
