<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaxMindDoNotSellPurgeCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Command\MaxMindDoNotSellPurgeCommand' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Command\MaxMindDoNotSellPurgeCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Command\\MaxMindDoNotSellPurgeCommand'] = new \Mautic\CoreBundle\Command\MaxMindDoNotSellPurgeCommand(($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)), ($container->services['Mautic\\LeadBundle\\Entity\\LeadRepository'] ?? self::getLeadRepository2Service($container)), ($container->services['mautic.maxmind.doNotSellList'] ?? $container->load('getMautic_Maxmind_DoNotSellListService')));
    }
}
