<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Form_Type_DwcEntryFiltersService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.form.type.dwc_entry_filters' shared service.
     *
     * @return \Mautic\DynamicContentBundle\Form\Type\DwcEntryFiltersType
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? self::getListModelService($container));

        if (isset($container->services['mautic.form.type.dwc_entry_filters'])) {
            return $container->services['mautic.form.type.dwc_entry_filters'];
        }

        $container->services['mautic.form.type.dwc_entry_filters'] = $instance = new \Mautic\DynamicContentBundle\Form\Type\DwcEntryFiltersType(($container->services['translator'] ?? self::getTranslator2Service($container)), $a);

        $instance->setConnection(($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container)));

        return $instance;
    }
}
