<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonitoringService extends AppKernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.0YpBH7M.MauticPlugin\MauticSocialBundle\Entity\Monitoring' shared service.
     *
     * @return \MauticPlugin\MauticSocialBundle\Entity\Monitoring
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.0YpBH7M": it needs an instance of "MauticPlugin\\MauticSocialBundle\\Entity\\Monitoring" but this type has been excluded in "Config/services.php".');
    }
}
