<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Focus_Helper_TokenService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.focus.helper.token' shared service.
     *
     * @return \MauticPlugin\MauticFocusBundle\Helper\TokenHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['MauticPlugin\\MauticFocusBundle\\Model\\FocusModel'] ?? self::getFocusModelService($container));

        if (isset($container->services['mautic.focus.helper.token'])) {
            return $container->services['mautic.focus.helper.token'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['mautic.focus.helper.token'])) {
            return $container->services['mautic.focus.helper.token'];
        }

        return $container->services['mautic.focus.helper.token'] = new \MauticPlugin\MauticFocusBundle\Helper\TokenHelper($a, $b, ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)));
    }
}
