<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Webhook_Notificator_WebhookkillnotificatorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.webhook.notificator.webhookkillnotificator' shared service.
     *
     * @return \Mautic\WebhookBundle\Notificator\WebhookKillNotificator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['mautic.webhook.notificator.webhookkillnotificator'])) {
            return $container->services['mautic.webhook.notificator.webhookkillnotificator'];
        }
        $b = ($container->services['Mautic\\CoreBundle\\Model\\NotificationModel'] ?? self::getNotificationModelService($container));

        if (isset($container->services['mautic.webhook.notificator.webhookkillnotificator'])) {
            return $container->services['mautic.webhook.notificator.webhookkillnotificator'];
        }
        $c = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['mautic.webhook.notificator.webhookkillnotificator'])) {
            return $container->services['mautic.webhook.notificator.webhookkillnotificator'];
        }
        $d = ($container->services['Mautic\\EmailBundle\\Helper\\MailHelper'] ?? self::getMailHelperService($container));

        if (isset($container->services['mautic.webhook.notificator.webhookkillnotificator'])) {
            return $container->services['mautic.webhook.notificator.webhookkillnotificator'];
        }

        return $container->services['mautic.webhook.notificator.webhookkillnotificator'] = new \Mautic\WebhookBundle\Notificator\WebhookKillNotificator(($container->services['translator'] ?? self::getTranslator2Service($container)), $a, $b, $c, $d, ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
