<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Integrations_Sync_DataExchange_Mautic_FieldBuilderService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.integrations.sync.data_exchange.mautic.field_builder' shared service.
     *
     * @return \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\ReportBuilder\FieldBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.integrations.sync.data_exchange.mautic.field_builder'] = new \Mautic\IntegrationsBundle\Sync\SyncDataExchange\Internal\ReportBuilder\FieldBuilder(($container->services['router'] ?? self::getRouterService($container)), ($container->services['Mautic\\IntegrationsBundle\\Sync\\SyncDataExchange\\Helper\\FieldHelper'] ?? $container->load('getFieldHelperService')), ($container->services['Mautic\\IntegrationsBundle\\Sync\\SyncDataExchange\\Internal\\ObjectHelper\\ContactObjectHelper'] ?? $container->load('getContactObjectHelperService')));
    }
}
