<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Page_Helper_TrackingService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.page.helper.tracking' shared service.
     *
     * @return \Mautic\PageBundle\Helper\TrackingHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Tracker\\ContactTracker'] ?? self::getContactTrackerService($container));

        if (isset($container->services['mautic.page.helper.tracking'])) {
            return $container->services['mautic.page.helper.tracking'];
        }

        return $container->services['mautic.page.helper.tracking'] = new \Mautic\PageBundle\Helper\TrackingHelper($a, ($container->services['mautic.cache.provider'] ?? self::getMautic_Cache_ProviderService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
