<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Email_Validator_EmailOrTokenListValidatorService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.email.validator.email_or_token_list_validator' shared service.
     *
     * @return \Mautic\EmailBundle\Validator\EmailOrEmailTokenListValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.validator.email'] ?? self::getMautic_Validator_EmailService($container));

        if (isset($container->services['mautic.email.validator.email_or_token_list_validator'])) {
            return $container->services['mautic.email.validator.email_or_token_list_validator'];
        }
        $b = ($container->services['mautic.lead.validator.custom_field'] ?? $container->load('getMautic_Lead_Validator_CustomFieldService'));

        if (isset($container->services['mautic.email.validator.email_or_token_list_validator'])) {
            return $container->services['mautic.email.validator.email_or_token_list_validator'];
        }

        return $container->services['mautic.email.validator.email_or_token_list_validator'] = new \Mautic\EmailBundle\Validator\EmailOrEmailTokenListValidator($a, $b);
    }
}
