<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Social_Helper_TwitterCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.social.helper.twitter_command' shared service.
     *
     * @return \MauticPlugin\MauticSocialBundle\Helper\TwitterCommandHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.social.helper.twitter_command'] = new \MauticPlugin\MauticSocialBundle\Helper\TwitterCommandHelper(($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? self::getLeadModelService($container)), ($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? self::getFieldModel2Service($container)), ($container->services['MauticPlugin\\MauticSocialBundle\\Model\\MonitoringModel'] ?? $container->load('getMonitoringModelService')), ($container->services['MauticPlugin\\MauticSocialBundle\\Model\\PostCountModel'] ?? $container->load('getPostCountModelService')), ($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
