<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMauticFactoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CoreBundle\Factory\MauticFactory' shared autowired service.
     *
     * @return \Mautic\CoreBundle\Factory\MauticFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CoreBundle\\Factory\\MauticFactory'] = new \Mautic\CoreBundle\Factory\MauticFactory(($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container)));
    }
}
