<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Update_Step_FinalizeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.update.step.finalize' shared service.
     *
     * @return \Mautic\CoreBundle\Update\Step\FinalizeUpdateStep
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.update.step.finalize'] = new \Mautic\CoreBundle\Update\Step\FinalizeUpdateStep(($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.helper.paths'] ?? self::getMautic_Helper_PathsService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['mautic.helper.app_version'] ??= new \Mautic\CoreBundle\Helper\AppVersion()));
    }
}
