<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Lead_Validator_CustomFieldService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.lead.validator.custom_field' shared service.
     *
     * @return \Mautic\LeadBundle\Validator\CustomFieldValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\FieldModel'] ?? self::getFieldModel2Service($container));

        if (isset($container->services['mautic.lead.validator.custom_field'])) {
            return $container->services['mautic.lead.validator.custom_field'];
        }

        return $container->services['mautic.lead.validator.custom_field'] = new \Mautic\LeadBundle\Validator\CustomFieldValidator($a, ($container->services['translator'] ?? self::getTranslator2Service($container)));
    }
}
