<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Security_UserTokenSetterService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.security.user_token_setter' shared service.
     *
     * @return \Mautic\UserBundle\Security\UserTokenSetter
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.security.user_token_setter'] = new \Mautic\UserBundle\Security\UserTokenSetter(($container->services['Mautic\\UserBundle\\Model\\UserModel'] ?? self::getUserModelService($container)), ($container->privates['security.token_storage'] ?? self::getSecurity_TokenStorageService($container)));
    }
}
