<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Campaign_ContactFinder_ScheduledService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.campaign.contact_finder.scheduled' shared service.
     *
     * @return \Mautic\CampaignBundle\Executioner\ContactFinder\ScheduledContactFinder
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['mautic.campaign.contact_finder.scheduled'] = new \Mautic\CampaignBundle\Executioner\ContactFinder\ScheduledContactFinder(($container->services['Mautic\\LeadBundle\\Entity\\LeadRepository'] ?? self::getLeadRepository2Service($container)), ($container->services['monolog.logger.mautic'] ?? self::getMonolog_Logger_MauticService($container)));
    }
}
