<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Security_LogoutHandlerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.security.logout_handler' shared service.
     *
     * @return \Mautic\UserBundle\EventListener\LogoutListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\UserBundle\\Model\\UserModel'] ?? self::getUserModelService($container));

        if (isset($container->services['mautic.security.logout_handler'])) {
            return $container->services['mautic.security.logout_handler'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['mautic.security.logout_handler'])) {
            return $container->services['mautic.security.logout_handler'];
        }

        return $container->services['mautic.security.logout_handler'] = new \Mautic\UserBundle\EventListener\LogoutListener($a, $b, ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)));
    }
}
