<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMautic_Helper_TokenBuilder_FactoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'mautic.helper.token_builder.factory' shared service.
     *
     * @return \Mautic\CoreBundle\Helper\BuilderTokenHelperFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container));

        if (isset($container->services['mautic.helper.token_builder.factory'])) {
            return $container->services['mautic.helper.token_builder.factory'];
        }
        $b = ($container->services['doctrine.dbal.default_connection'] ?? self::getDoctrine_Dbal_DefaultConnectionService($container));

        if (isset($container->services['mautic.helper.token_builder.factory'])) {
            return $container->services['mautic.helper.token_builder.factory'];
        }

        return $container->services['mautic.helper.token_builder.factory'] = new \Mautic\CoreBundle\Helper\BuilderTokenHelperFactory(($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), $a, $b, ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)));
    }
}
