<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNotificationSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\NotificationBundle\EventListener\NotificationSubscriber' shared autowired service.
     *
     * @return \Mautic\NotificationBundle\EventListener\NotificationSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Model\\AuditLogModel'] ?? self::getAuditLogModelService($container));

        if (isset($container->services['Mautic\\NotificationBundle\\EventListener\\NotificationSubscriber'])) {
            return $container->services['Mautic\\NotificationBundle\\EventListener\\NotificationSubscriber'];
        }
        $b = ($container->services['Mautic\\PageBundle\\Model\\TrackableModel'] ?? self::getTrackableModelService($container));

        if (isset($container->services['Mautic\\NotificationBundle\\EventListener\\NotificationSubscriber'])) {
            return $container->services['Mautic\\NotificationBundle\\EventListener\\NotificationSubscriber'];
        }

        return $container->services['Mautic\\NotificationBundle\\EventListener\\NotificationSubscriber'] = new \Mautic\NotificationBundle\EventListener\NotificationSubscriber($a, $b, ($container->services['mautic.page.helper.token'] ?? self::getMautic_Page_Helper_TokenService($container)), ($container->services['Mautic\\AssetBundle\\Helper\\TokenHelper'] ?? self::getTokenHelperService($container)));
    }
}
