<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticFocusBundle\EventListener\PageSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticFocusBundle\EventListener\PageSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['MauticPlugin\\MauticFocusBundle\\Model\\FocusModel'] ?? self::getFocusModelService($container));

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\PageSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\PageSubscriber'];
        }
        $b = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\PageSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\PageSubscriber'];
        }
        $c = ($container->services['mautic.helper.token_builder.factory'] ?? $container->load('getMautic_Helper_TokenBuilder_FactoryService'));

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\PageSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\PageSubscriber'];
        }

        return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\PageSubscriber'] = new \MauticPlugin\MauticFocusBundle\EventListener\PageSubscriber(($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), $a, $b, $c);
    }
}
