<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPageSubscriber5Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\NotificationBundle\EventListener\PageSubscriber' shared autowired service.
     *
     * @return \Mautic\NotificationBundle\EventListener\PageSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Twig\\Helper\\AssetsHelper'] ?? self::getAssetsHelperService($container));

        if (isset($container->services['Mautic\\NotificationBundle\\EventListener\\PageSubscriber'])) {
            return $container->services['Mautic\\NotificationBundle\\EventListener\\PageSubscriber'];
        }
        $b = ($container->services['mautic.helper.integration'] ?? self::getMautic_Helper_IntegrationService($container));

        if (isset($container->services['Mautic\\NotificationBundle\\EventListener\\PageSubscriber'])) {
            return $container->services['Mautic\\NotificationBundle\\EventListener\\PageSubscriber'];
        }

        return $container->services['Mautic\\NotificationBundle\\EventListener\\PageSubscriber'] = new \Mautic\NotificationBundle\EventListener\PageSubscriber($a, $b);
    }
}
