<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPasswordStrengthSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\UserBundle\EventListener\PasswordStrengthSubscriber' shared autowired service.
     *
     * @return \Mautic\UserBundle\EventListener\PasswordStrengthSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\UserBundle\\EventListener\\PasswordStrengthSubscriber'] = new \Mautic\UserBundle\EventListener\PasswordStrengthSubscriber();
    }
}
