<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPluginSubscriber2Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\PluginBundle\EventListener\PluginSubscriber' shared autowired service.
     *
     * @return \Mautic\PluginBundle\EventListener\PluginSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\PluginBundle\\Bundle\\PluginDatabase'] ?? $container->load('getPluginDatabaseService'));

        if (isset($container->services['Mautic\\PluginBundle\\EventListener\\PluginSubscriber'])) {
            return $container->services['Mautic\\PluginBundle\\EventListener\\PluginSubscriber'];
        }

        return $container->services['Mautic\\PluginBundle\\EventListener\\PluginSubscriber'] = new \Mautic\PluginBundle\EventListener\PluginSubscriber($a);
    }
}
