<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReplyService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\EmailBundle\MonitoredEmail\Processor\Reply' shared autowired service.
     *
     * @return \Mautic\EmailBundle\MonitoredEmail\Processor\Reply
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\EmailBundle\\Model\\EmailStatModel'] ?? self::getEmailStatModelService($container));

        if (isset($container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'])) {
            return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'];
        }
        $b = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? self::getLeadModelService($container));

        if (isset($container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'])) {
            return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'];
        }
        $c = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'])) {
            return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'];
        }
        $d = ($container->services['Mautic\\LeadBundle\\Tracker\\ContactTracker'] ?? self::getContactTrackerService($container));

        if (isset($container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'])) {
            return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'];
        }

        return $container->services['Mautic\\EmailBundle\\MonitoredEmail\\Processor\\Reply'] = new \Mautic\EmailBundle\MonitoredEmail\Processor\Reply($a, ($container->services['mautic.message.search.contact'] ?? $container->load('getMautic_Message_Search_ContactService')), $b, $c, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), $d, ($container->services['Mautic\\CoreBundle\\Helper\\EmailAddressHelper'] ??= new \Mautic\CoreBundle\Helper\EmailAddressHelper()));
    }
}
