<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchSubscriber15Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\SmsBundle\EventListener\SearchSubscriber' shared autowired service.
     *
     * @return \Mautic\SmsBundle\EventListener\SearchSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\SmsBundle\\Model\\SmsModel'] ?? $container->load('getSmsModelService'));

        if (isset($container->services['Mautic\\SmsBundle\\EventListener\\SearchSubscriber'])) {
            return $container->services['Mautic\\SmsBundle\\EventListener\\SearchSubscriber'];
        }

        return $container->services['Mautic\\SmsBundle\\EventListener\\SearchSubscriber'] = new \Mautic\SmsBundle\EventListener\SearchSubscriber($a, ($container->services['Mautic\\CoreBundle\\Service\\GlobalSearch'] ?? $container->load('getGlobalSearchService')));
    }
}
