<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchSubscriber16Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\StageBundle\EventListener\SearchSubscriber' shared autowired service.
     *
     * @return \Mautic\StageBundle\EventListener\SearchSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\StageBundle\\Model\\StageModel'] ?? $container->load('getStageModelService'));

        if (isset($container->services['Mautic\\StageBundle\\EventListener\\SearchSubscriber'])) {
            return $container->services['Mautic\\StageBundle\\EventListener\\SearchSubscriber'];
        }

        return $container->services['Mautic\\StageBundle\\EventListener\\SearchSubscriber'] = new \Mautic\StageBundle\EventListener\SearchSubscriber($a, ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), ($container->services['Mautic\\CoreBundle\\Service\\GlobalSearch'] ?? $container->load('getGlobalSearchService')));
    }
}
