<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStageModelService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\StageBundle\Model\StageModel' shared autowired service.
     *
     * @return \Mautic\StageBundle\Model\StageModel
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? self::getLeadModelService($container));

        if (isset($container->services['Mautic\\StageBundle\\Model\\StageModel'])) {
            return $container->services['Mautic\\StageBundle\\Model\\StageModel'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['Mautic\\StageBundle\\Model\\StageModel'])) {
            return $container->services['Mautic\\StageBundle\\Model\\StageModel'];
        }
        $c = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['Mautic\\StageBundle\\Model\\StageModel'])) {
            return $container->services['Mautic\\StageBundle\\Model\\StageModel'];
        }

        return $container->services['Mautic\\StageBundle\\Model\\StageModel'] = new \Mautic\StageBundle\Model\StageModel($a, ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)), ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), $b, $c, ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['monolog.logger.mautic'] ?? self::getMonolog_Logger_MauticService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
