<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatsSubscriber15Service extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\WebhookBundle\EventListener\StatsSubscriber' shared autowired service.
     *
     * @return \Mautic\WebhookBundle\EventListener\StatsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\WebhookBundle\\EventListener\\StatsSubscriber'] = new \Mautic\WebhookBundle\EventListener\StatsSubscriber(($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), ($container->services['mautic.permission.manager'] ?? self::getMautic_Permission_ManagerService($container)));
    }
}
