<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetContactAvatarFormSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\SetContactAvatarFormSubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\SetContactAvatarFormSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\LeadBundle\\Model\\LeadModel'] ?? self::getLeadModelService($container));

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\SetContactAvatarFormSubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\SetContactAvatarFormSubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\SetContactAvatarFormSubscriber'] = new \Mautic\LeadBundle\EventListener\SetContactAvatarFormSubscriber(($container->services['mautic.helper.twig.avatar'] ?? self::getMautic_Helper_Twig_AvatarService($container)), ($container->services['mautic.form.helper.form_uploader'] ?? self::getMautic_Form_Helper_FormUploaderService($container)), $a);
    }
}
