<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSmsSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\SmsBundle\EventListener\SmsSubscriber' shared autowired service.
     *
     * @return \Mautic\SmsBundle\EventListener\SmsSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['Mautic\\CoreBundle\\Model\\AuditLogModel'] ?? self::getAuditLogModelService($container));

        if (isset($container->services['Mautic\\SmsBundle\\EventListener\\SmsSubscriber'])) {
            return $container->services['Mautic\\SmsBundle\\EventListener\\SmsSubscriber'];
        }
        $b = ($container->services['Mautic\\PageBundle\\Model\\TrackableModel'] ?? self::getTrackableModelService($container));

        if (isset($container->services['Mautic\\SmsBundle\\EventListener\\SmsSubscriber'])) {
            return $container->services['Mautic\\SmsBundle\\EventListener\\SmsSubscriber'];
        }
        $c = ($container->services['mautic.helper.sms'] ?? $container->load('getMautic_Helper_SmsService'));

        if (isset($container->services['Mautic\\SmsBundle\\EventListener\\SmsSubscriber'])) {
            return $container->services['Mautic\\SmsBundle\\EventListener\\SmsSubscriber'];
        }

        return $container->services['Mautic\\SmsBundle\\EventListener\\SmsSubscriber'] = new \Mautic\SmsBundle\EventListener\SmsSubscriber($a, $b, ($container->services['mautic.page.helper.token'] ?? self::getMautic_Page_Helper_TokenService($container)), ($container->services['Mautic\\AssetBundle\\Helper\\TokenHelper'] ?? self::getTokenHelperService($container)), $c, ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
