<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSearchSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticFocusBundle\EventListener\SearchSubscriber' shared autowired service.
     *
     * @return \MauticPlugin\MauticFocusBundle\EventListener\SearchSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['MauticPlugin\\MauticFocusBundle\\Model\\FocusModel'] ?? self::getFocusModelService($container));

        if (isset($container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\SearchSubscriber'])) {
            return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\SearchSubscriber'];
        }

        return $container->services['MauticPlugin\\MauticFocusBundle\\EventListener\\SearchSubscriber'] = new \MauticPlugin\MauticFocusBundle\EventListener\SearchSubscriber($a, ($container->services['Mautic\\CoreBundle\\Service\\GlobalSearch'] ?? $container->load('getGlobalSearchService')));
    }
}
