<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_HttpBasic_ApiService extends AppKernelProdContainer
{
    /*
     * Gets the private 'security.authenticator.http_basic.api' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\HttpBasicAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['mautic.user.provider'] ?? self::getMautic_User_ProviderService($container));

        if (isset($container->privates['security.authenticator.http_basic.api'])) {
            return $container->privates['security.authenticator.http_basic.api'];
        }

        return $container->privates['security.authenticator.http_basic.api'] = new \Symfony\Component\Security\Http\Authenticator\HttpBasicAuthenticator('Secured Area', $a, ($container->privates['monolog.logger.security'] ?? self::getMonolog_Logger_SecurityService($container)));
    }
}
