<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimelineEventLogSegmentSubscriberService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\EventListener\TimelineEventLogSegmentSubscriber' shared autowired service.
     *
     * @return \Mautic\LeadBundle\EventListener\TimelineEventLogSegmentSubscriber
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['Mautic\\LeadBundle\\EventListener\\TimelineEventLogSegmentSubscriber'])) {
            return $container->services['Mautic\\LeadBundle\\EventListener\\TimelineEventLogSegmentSubscriber'];
        }

        return $container->services['Mautic\\LeadBundle\\EventListener\\TimelineEventLogSegmentSubscriber'] = new \Mautic\LeadBundle\EventListener\TimelineEventLogSegmentSubscriber(($container->services['Mautic\\LeadBundle\\Entity\\LeadEventLogRepository'] ?? $container->load('getLeadEventLogRepository2Service')), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), $a);
    }
}
