<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagControllerService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticTagManagerBundle\Controller\TagController' shared autowired service.
     *
     * @return \MauticPlugin\MauticTagManagerBundle\Controller\TagController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['MauticPlugin\\MauticTagManagerBundle\\Controller\\TagController'] = $instance = new \MauticPlugin\MauticTagManagerBundle\Controller\TagController(($container->privates['form.factory'] ?? self::getForm_FactoryService($container)), ($container->services['mautic.helper.form.field_helper'] ?? self::getMautic_Helper_Form_FieldHelperService($container)), ($container->services['doctrine'] ?? self::getDoctrineService($container)), ($container->services['Mautic\\CoreBundle\\Factory\\ModelFactory'] ?? self::getModelFactoryService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.core.service.flashbag'] ?? self::getMautic_Core_Service_FlashbagService($container)), ($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? self::get_ServiceLocator_O2p6Lk7Service($container))->withContext('MauticPlugin\\MauticTagManagerBundle\\Controller\\TagController', $container));

        return $instance;
    }
}
