<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTagModelService extends AppKernelProdContainer
{
    /*
     * Gets the public 'MauticPlugin\MauticTagManagerBundle\Model\TagModel' shared autowired service.
     *
     * @return \MauticPlugin\MauticTagManagerBundle\Model\TagModel
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->services['MauticPlugin\\MauticTagManagerBundle\\Model\\TagModel'])) {
            return $container->services['MauticPlugin\\MauticTagManagerBundle\\Model\\TagModel'];
        }
        $b = ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container));

        if (isset($container->services['MauticPlugin\\MauticTagManagerBundle\\Model\\TagModel'])) {
            return $container->services['MauticPlugin\\MauticTagManagerBundle\\Model\\TagModel'];
        }
        $c = ($container->services['router'] ?? self::getRouterService($container));

        if (isset($container->services['MauticPlugin\\MauticTagManagerBundle\\Model\\TagModel'])) {
            return $container->services['MauticPlugin\\MauticTagManagerBundle\\Model\\TagModel'];
        }

        return $container->services['MauticPlugin\\MauticTagManagerBundle\\Model\\TagModel'] = new \MauticPlugin\MauticTagManagerBundle\Model\TagModel($a, ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), $b, $c, ($container->services['Mautic\\CoreBundle\\Translation\\Translator'] ?? self::getTranslatorService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
