<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTriggerCampaignCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\CampaignBundle\Command\TriggerCampaignCommand' shared autowired service.
     *
     * @return \Mautic\CampaignBundle\Command\TriggerCampaignCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\CampaignBundle\\Command\\TriggerCampaignCommand'] = new \Mautic\CampaignBundle\Command\TriggerCampaignCommand(($container->services['Mautic\\CampaignBundle\\Entity\\CampaignRepository'] ?? $container->load('getCampaignRepositoryService')), ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.campaign.executioner.kickoff'] ?? $container->load('getMautic_Campaign_Executioner_KickoffService')), ($container->services['Mautic\\CampaignBundle\\Executioner\\ScheduledExecutioner'] ?? $container->load('getScheduledExecutionerService')), ($container->services['Mautic\\CampaignBundle\\Executioner\\InactiveExecutioner'] ?? $container->load('getInactiveExecutionerService')), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), ($container->services['mautic.helper.twig.formatter'] ?? self::getMautic_Helper_Twig_FormatterService($container)), ($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? self::getListModelService($container)), ($container->services['mautic.helper.segment.count.cache'] ?? self::getMautic_Helper_Segment_Count_CacheService($container)), ($container->services['mautic.helper.paths'] ?? self::getMautic_Helper_PathsService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
