<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserStepTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\InstallBundle\Configurator\Form\UserStepType' shared autowired service.
     *
     * @return \Mautic\InstallBundle\Configurator\Form\UserStepType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\InstallBundle\\Configurator\\Form\\UserStepType'] = new \Mautic\InstallBundle\Configurator\Form\UserStepType(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
