<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPreferencesTypeService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\UserBundle\Form\Type\UserPreferencesType' shared autowired service.
     *
     * @return \Mautic\UserBundle\Form\Type\UserPreferencesType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\UserBundle\\Form\\Type\\UserPreferencesType'] = new \Mautic\UserBundle\Form\Type\UserPreferencesType();
    }
}
