<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUpdateLeadListsCommandService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\LeadBundle\Command\UpdateLeadListsCommand' shared autowired service.
     *
     * @return \Mautic\LeadBundle\Command\UpdateLeadListsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\LeadBundle\\Command\\UpdateLeadListsCommand'] = new \Mautic\LeadBundle\Command\UpdateLeadListsCommand(($container->services['Mautic\\LeadBundle\\Model\\ListModel'] ?? self::getListModelService($container)), ($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.helper.paths'] ?? self::getMautic_Helper_PathsService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)));
    }
}
