<?php

namespace ContainerEEzbBj8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWidgetDetailEventFactoryService extends AppKernelProdContainer
{
    /*
     * Gets the public 'Mautic\DashboardBundle\Factory\WidgetDetailEventFactory' shared autowired service.
     *
     * @return \Mautic\DashboardBundle\Factory\WidgetDetailEventFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->services['Mautic\\DashboardBundle\\Factory\\WidgetDetailEventFactory'] = new \Mautic\DashboardBundle\Factory\WidgetDetailEventFactory(($container->services['translator'] ?? self::getTranslator2Service($container)), ($container->services['mautic.cache.provider'] ?? self::getMautic_Cache_ProviderService($container)), ($container->services['mautic.security'] ?? self::getMautic_SecurityService($container)), ($container->services['mautic.helper.user'] ?? self::getMautic_Helper_UserService($container)), ($container->services['mautic.helper.core_parameters'] ??= new \Mautic\CoreBundle\Helper\CoreParametersHelper($container)), ($container->services['mautic.helper.paths'] ?? self::getMautic_Helper_PathsService($container)));
    }
}
