enabled: true
dropdown:
  enabled: true
sticky_menu:
  enabled: false
production-mode: false
custom_css: '0'
custom_js: '0'
social_enabled: true
social:
  -
    name: Facebook
    url: '#'
    target: _blank
    icon: 'fa fa-facebook'
  -
    name: Instagram
    url: 'https://www.instagram.com/hukawati.es/'
    target: _self
    icon: 'fa fa-instagram'
  -
    name: 'Send Mail'
    url: 'mailto:#'
    target: _self
    icon: 'fa fa-envelope-o'
footer:
  copyright_text: 'Copyright 2025 Salina Shelton'
  contact_section_label: Contact
  quick_links_label: 'Quick Links'
  about:
    description: 'Salina Shelton is a licensed counselor and certified art therapist in San Antonio who integrates art into mental-health care, leaders multiple community healing organizations—HopeWise, Grow Creative, and formerly the Chronic Pain Resource Center—and champions a holistic, trauma-informed approach to wellness.'
  gps: null
  address:
    -
      line: '980 Talley Rd'
    -
      line: 'San Antonio, Tx'
    -
      line: US
  quick_links_items:
    -
      text: Portfolio
      url: portfolio
      target: _self
    -
      text: About
      url: about
      target: _self
    -
      text: Services
      url: services
      target: _self
    -
      text: Archive
      url: archive
      target: _self
    -
      text: Blog
      url: blog
      target: _self
    -
      text: 'Contact Us'
      url: contact
      target: _self
  other_menu:
    -
      text: About
      url: about
      target: _self
    -
      text: 'Privacy Policy'
      url: '#'
      target: _self
    -
      text: Contact
      url: contact
      target: _self
custommenus:
  enabled: true
custommenu:
  -
    text: 'Grow Creative'
    icon: home
    url: 'https://growcreativesa.com'
    target: _blank
theme_logo_enabled: true
type_logo_header: text
theme_logo:
  user/themes/delivernext/images/logo/849124DF-CA6E-4289-88D2-DD73CDAF622E_1_105_c.jpeg:
    name: 849124DF-CA6E-4289-88D2-DD73CDAF622E_1_105_c.jpeg
    full_path: 849124DF-CA6E-4289-88D2-DD73CDAF622E_1_105_c.jpeg
    type: image/jpeg
    size: 118374
    path: user/themes/delivernext/images/logo/849124DF-CA6E-4289-88D2-DD73CDAF622E_1_105_c.jpeg
theme_logo_mobile: {  }
back_to_top_button:
  enabled: true
